US7 bruger login
mrPrimeBeef/FogCarport pull request #15
Opened 2024-12-04 10:19 UTC by Agnethechr

I've created a getAccountByEmail method in AccountMapper, a forgotPassword method in AccountController, a glemtKode html and updatede our error html page. forgotPassword method uses the PasswordGenerator to generate a random password the prints both the email and new password for the user email entered on the glemtKode html page. Right now the password changes every time the user writes the email on the glemtKode html page. 

Some fixes: need to fix the footer on the error html page, login (maybe it is just mine, but the funktion doesn't work :/ )
More styling?

2024-12-04 10:51 UTC, mrPrimeBeef commented on src/main/java/app/entities/Account.java
> -    public Account(int accountId, String role) {
Dette skal ikke slettes

2024-12-04 10:51 UTC, mrPrimeBeef commented on src/main/java/app/persistence/AccountMapper.java
>                  String role = rs.getString("role");
hvorfor er re.getstring(email) inde i contrutoren og ikke som de andre?

2024-12-04 10:51 UTC, mrPrimeBeef commented on src/main/java/app/controllers/AccountController.java
> +            if ("customer".equals(role)) {
dette skal være "Kunde"

2024-12-04 10:51 UTC, mrPrimeBeef commented on src/main/java/app/controllers/AccountController.java
> +                ctx.render("error.html");
Kunne den ikke bare loade glemtkode siden og give error beskeden der?

2024-12-04 10:51 UTC, mrPrimeBeef commented on src/main/java/app/controllers/AccountController.java
> +            ctx.attribute("errorMessage", "Ugyldig brugertype.");
slet

2024-12-04 11:48 UTC, Agnethechr commented on src/main/java/app/controllers/AccountController.java
> +                ctx.render("error.html");
Har oprettet en errorMessage og lagt den ind i glemtKode html og lavet tekst farven rød.

2024-12-04 11:49 UTC, Agnethechr commented on src/main/java/app/controllers/AccountController.java
> +            if ("customer".equals(role)) {
Har ændret det til Kunde, skal salesrep også ændres til noget andet?

2024-12-04 11:56 UTC, Agnethechr commented on src/main/java/app/controllers/AccountController.java
> +            ctx.attribute("errorMessage", "Ugyldig brugertype.");
Jeg har bare lavet en else, for jeg prøvede med to forskellige mails og jeg fik begge fejl beskeder ud? Mystisk, du må gerne kigge på det med mig, når du har tid?

2024-12-04 11:57 UTC, Agnethechr commented on src/main/java/app/entities/Account.java
> -    public Account(int accountId, String role) {
Jeg har tilføjet den igen :)

2024-12-05 09:32 UTC, Agnethechr reviewed
Jeg har rettet tingene, men vi skal nok lige rette vores database så det er Kunde og salesrep eller saelger?

2024-12-05 10:06 UTC, mrPrimeBeef commented on src/main/java/app/controllers/AccountController.java
> +                System.out.println("Den indtastet email: " + email + "\n" + "Adgangskoden for den indtastet mail er: " + newPassword);
Den nye mail gemmes ikke i database

2024-12-05 10:07 UTC, mrPrimeBeef requested changes
Den nye mail gemmes ikke i database, det skal kaldes i account controlleren, dvs. der skal laves en metode i accountMapper som updatere det i DB

2024-12-06 08:26 UTC, merged